version: "3.9"

services:
  backend:
    build: .
    ports:
      - 9000:9000
    volumes:
      - .:/app
  # database connection and creation
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: shop-sample
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
      # map mysql port to a different port
    ports:
      - 33066:3306
